### ISSUE TITLE
Update IDz calendar page

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#10]
A new schedule for IDz training for 3Q has been added. This page does not reflect it yet.
https://ibm.github.io/mainframe-downloads/Training/idzrdz-remote-training.html

Can you please take the content from https://ibm.biz/zDevOpsClasses under **IDz/ADFz/RDz Entry-Level and Experienced User Training Schedule**, specifically the new dates/times and topics and copy them to the GitHub page?
I like the layout you have on the GitHub page, its much cleaner, so lets maintain that layout please.

**Comment by jerryxz-ibm** [comment]
Issue resolved.
