### ISSUE TITLE
Create new landing page for ADDI

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#11]
Similar to the DBB landing page which is at https://ibm.github.io/mainframe-downloads/Training/dbb-self-paced-learning.html, please create a new one for ADDI.
Please make the link be https://ibm.github.io/mainframe-downloads/Training/addi-self-paced-learning.html.

Content to change:
1) The title should change to **IBM Application Discovery & Delivery Intelligence Essentials**
2) The subtitle should change to **Static source analysis for application modernization with IBM ADDI**
3) Above the **Badge Overview** section, create a **Launch the course** section, with the description pointing to https://learn.ibm.com/course/view.php?id=7680
4) **Badge Overview** section - update description to _Digital credentials are the future and they are here for Application Discovery & Delivery Intelligence (ADDI). Digital credentials are transforming how IBM is engaging, recognising and managing talent. The course is designed to provide the audience with an introduction to Static source analysis for application modernization with IBM ADDI._
5) **Badge Description** section - update Description to 
_The badge holder has successfully completed the self paced online course and zTrial Lab, covering the following modules:
Upon completion of this course, students will have the foundational knowledge on following topics:
Module 1 – ADDI Relationship with Digital Transformation
Module 2 – AD Product Overview, Terms, Concepts and Vocabulary
Module 3 – AD Eclipse Navigation and Introduction to Call Graphs
Module 4 – AD Detailed Analysis Reports
Module 5 – AD Resource Usage in Jobs and Programs
Module 6 – zTrial Overview & Workshops
Module 7 – Knowledge center reference and Badge Quiz

**What it takes to earn this badge**
Successful completion of the Application Discovery & Delivery Intelligence (ADDI) online self paced course and clearing the badge quiz assessment.
Please access the following URL to launch the course: https://learn.ibm.com/course/view.php?id=7680
You will receive your badge within 10 business days of completing the training curriculum. This badge can be obtained by any IBM employee or non-IBM employee.

**More about the IBM Digital Badge program**
IBM has established a Digital Badge Program to recognise our employees' significant achievements and skills attainment. IBM credentials are recognized, respected and valued globally in the IT industry. This program will enable you to easily and quickly share verified proof of your achievement both within IBM and externally. Where applicable, your IBM credentials will be represented by a digital image that contains verified metadata describing your qualifications and the rigorous process necessary to earn them.

**Badge Queries**
For questions about the DBB Basics badge program, such as a missing or incorrect badge or how to earn the badge, contact shabbirm@ca.ibm.com, dhawrel@us.ibm.com, jiachun.xiang@ibm.com
Acclaim Support: For questions related to your Acclaim badge earner account and profile, as well as issues related to claiming your badge after receiving a notification, go to http://support.youracclaim.com.

For Frequently Asked Questions about the IBM Digital Badge Program, click here.

**Badge Privacy Statement**
IBM leverages the services of Credly's Acclaim platform, a 3rd party data processor authorized by IBM and located in the United States, to assist in the administration of the IBM Digital Badge program. In order to issue you an IBM Digital Badge, your personal information (name, email address, and badge earned) will be shared with the Credly’s Acclaim platform. You will receive an email notification from Acclaim with instructions for claiming the badge. Your personal information is used to issue your badge and for program reporting and operational purposes. It will be handled in a manner consistent with IBM privacy practices. The IBM Privacy Statement can be viewed here: https://www.ibm.com/privacy/us/en/. IBM employees can view the IBM Internal Privacy Statement here: https://w3.ibm.com/w3publisher/w3-privacy-notice._

**Comment by jerryxz-ibm** [comment]
Created the expected page and added a link to the page from Training main page.
