### ISSUE TITLE
Change to the Training tiles

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#12]
I would like to request a small change to the training tiles, specifically to the second one (IDz Self Paced Learning) located here:
https://ibm.github.io/mainframe-downloads/Training/Training.html

For consistency, can you please rename the tile (and the title) to IBM Developer for Z , and have "Self-paced Learning" show up on it, similar to the DBB and ADDI tiles

**Comment by jerryxz-ibm** [comment]
Contents modified as required.
