### ISSUE TITLE
Creation of ADFz landing page

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#13]
Similar to the landing page that was recently created for ADDI, which is located at https://ibm.github.io/mainframe-downloads/Training/addi-self-paced-learning.html, can you please create a new one for ADFz? 
The link could be https://ibm.github.io/mainframe-downloads/Training/adfz-instructor-led-learning.html. The content should come from the attachment.
[ADFz_RDz_IDz – Do you have a Digital Badge for that_ - Mainframe DEV.pdf](https://github.com/IBM/mainframe-downloads/files/5513415/ADFz_RDz_IDz.Do.you.have.a.Digital.Badge.for.that_.-.Mainframe.DEV.pdf)

Once you have the skeleton in place, we can discuss what the links from the pdf should direct to.

**Comment by jerryxz-ibm** [comment]
@shabbirmoledina do we have the final version of the pdf content in Word?

**Comment by shabbirmoledina** [comment]
[ADFz-RDz-IDz Digital Badge_SM.docx](https://github.com/IBM/mainframe-downloads/files/5669250/ADFz-RDz-IDz.Digital.Badge_SM.docx)

Here is the document. Can you please create a page for it?

Once its ready, I will discuss with you where to link it from and to.

**Comment by jerryxz-ibm** [comment]
@shabbirmoledina the page is created at: https://ibm.github.io/mainframe-downloads/Training/adfz-instructor-led-learning.html
Please have a review, and if things are good, let me know where to place its link portal.

**Comment by shabbirmoledina** [comment]
It looks great. Just one change needed really.
1) Change the Title from "ADFz/RDz/IDz - Do you have a Digital Badge" to "ADFz/RDz/IDz - Foundations Course" Also add a subtitle "Instructor Led Training".
This will be similar to this page (https://ibm.github.io/mainframe-downloads/DevOps_Acceleration_Program/idz-self-paced-learning.html) where there is a subtitle for "Self paced Learning"

2) Once you have made the changes in (1) above, go to https://ibm.github.io/mainframe-downloads/Training/Training.html and under Training, for the first tile, rename it to ""ADFz/RDz/IDz - Foundations Course" with the subtext under it being "Instructor Led Training".

**Comment by jerryxz-ibm** [comment]
Fixed as requested.
