### ISSUE TITLE
Change link one one of DAP resources

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#15]
On this page, https://ibm.github.io/mainframe-downloads/DevOps_Acceleration_Program/resources.html, the third tech doc which is titled "Managing git credentials in Jenkins to access the central git provider" is pointing to the wrong link. 

Can you please have it point to
https://www.ibm.com/support/pages/node/6354897

**Comment by jerryxz-ibm** [comment]
Link updated.
