### ISSUE TITLE
Please add new tech doc to DAP Resources

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#16]
Can you please add this link (https://www.ibm.com/support/pages/node/6366801) as a new tile in the Tech Docs section of the DAP Resources webpage (https://ibm.github.io/mainframe-downloads/DevOps_Acceleration_Program/resources.html). Please title the Tile as **Setup your Groovy Development Environment in IDz**.

**Comment by jerryxz-ibm** [comment]
A new card is created for this at the Tech Docs section.
