### ISSUE TITLE
changes for EWM integration on eclipse-tools page

### ISSUE THREAD

**Issue by walexand4z** [IBM/mainframe-downloads#18]
On this page https://ibm.github.io/mainframe-downloads/eclipse-tools.html the following changes are neeed:
1) Change **IBM Rational Team Concert Integration for z/OS**  to **IBM Engineering Workflow Management Integration for z/OS**
2) Change the blue text that explains the offering so that it says:
This IBM Developer for z/OS extension provides the capability that allows Engineering Workflow Management to enable Remote project and User Build support for z/OS developers.

**Comment by jerryxz-ibm** [comment]
EWM fixes applied to the download wizard as well.
