### ISSUE TITLE
Add z/OS Connect EE Build Toolkit to Mainframe Downloads Page

### ISSUE THREAD

**Issue by Sam-Catling** [IBM/mainframe-downloads#19]
Hi, would it be possible to get the z/OS Connect EE Build Toolkit to be made available on this page: https://ibm.github.io/mainframe-downloads/downloads.html

Category: IBM Enterprise DevOps
Product name: IBM z/OS Connect EE Build Toolkit
Download link: https://www14.software.ibm.com/cgi-bin/weblap/lap.pl?popup=Y&li_formnum=L-ACRR-AVRDUP&accepted_url=https://public.dhe.ibm.com/ibmdl/export/pub/software/htp/zos/updates/zconbt.zip

**Comment by jerryxz-ibm** [comment]
A new row for this is created in the "IBM Enterprise DevOps" section.
