### ISSUE TITLE
ADFz training page - fix minor link issue

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#21]
On this page:
https://ibm.github.io/mainframe-downloads/Training/idzrdz-remote-training.html

In the "Getting Started Notes" section:
For the third bullet, please replace this line:
There is a short workshop setup process needed for the hands-on labs. See the table below for details- and please try to finish this before attending Module 1 here.

With

There is a short workshop setup process needed for the hands-on labs. See the table below in the **Setup** section for details- and please try to finish this before attending Module 1.

**Comment by jerryxz-ibm** [comment]
Link fixed.
