### ISSUE TITLE
Add new tech doc to Resources page on DAP website

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#22]
On this page (https://ibm.github.io/mainframe-downloads/DevOps_Acceleration_Program/resources.html), please add a new tile under the Tech Docs section and link it to https://www.ibm.com/support/pages/node/6381788. Please make the title of the tile "Managing the build scope in IBM DBB builds with IBM zAppBuild"

**Comment by jerryxz-ibm** [comment]
New tech doc tile added.
