### ISSUE TITLE
ADFz Badge migration page

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#3]
Can we please migrate the content of this ADFz badge landing page (https://developer.ibm.com/mainframe/adfzidzrdz-foundations-digital-badge/) to the new GitHub.io page?

Is it possible to make the new link https://ibm.github.io/mainframe-downloads/Training/adfzidzrdz-foundations-digital-badge/? 

Also, on the source page under "What it takes to earn this badge", there is a link to the IDz/RDz Remote Training page, can that link be updated to https://ibm.github.io/mainframe-downloads/Training/idzrdz-remote-training.html as well?

**Comment by jerryxz-ibm** [comment]
Issue resolved.
