### ISSUE TITLE
Enable individual product zip downloads for Aqua 3.2 (IM and p2 local repos), same as available in Aqua 3.1

### ISSUE THREAD

**Issue by polommmx** [IBM/mainframe-downloads#31]
In Aqua 3.2,  Individual product zip files should be enable when users select IM or p2 to download and host repos locally, here the options involved:

IBM Installation Manager > Hosting an internal Installation Manager repository 
Eclipse p2 > Hosting an internal repository 

3.2 offers to download all products for either IM or p2 in one big file and while enabling individual zips, one big zip file functionality must be preserved in Aqua 3.2.

**Comment by jerryxz-ibm** [comment]
Implemented a solution similar to Aqua 3.1 - enabled individual offerings downloads as zip files. Tested with both IM and P2 installs.
