### ISSUE TITLE
Zowe integration web page needs updates

### ISSUE THREAD

**Issue by Domenico224** [IBM/mainframe-downloads#32]
Hello,
in the Zowe integration part of this page https://ibm.github.io/mainframe-downloads/downloads.html a couple of updates are needed.
IBM Z Service Automation Suite, the most recent version available is 1.3, please update it. Moreover the link to the Documentation should be updated to this one: https://www.ibm.com/support/knowledgecenter/SS9PZ4
IBM Service Management Unite, the most recent version available is 1.1.8, please update it.

Thank you

**Comment by jerryxz-ibm** [comment]
Updates are made. Thanks.
