### ISSUE TITLE
Update contents of the ADFz Resources page

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#38]
Hi Jerry,

Can you please copy over the contents (and associated links) from https://community.ibm.com/community/user/ibmz-and-linuxone/viewdocument/idzadfzaddi-index-of-product-trai-2?CommunityKey=b0dae4a8-74eb-44ac-86c7-90f3cd32909a&tab=librarydocuments to https://ibm.github.io/mainframe-downloads/Training/adfz-learning-resources.html?

There have been some new videos/documents added, and rather than identifying what has changed, it may be easier to simply rip and replace.

Thank you,
Shabbir

**Comment by jerryxz-ibm** [comment]
Contents updated.
