### ISSUE TITLE
Sync the training calendar pages

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#39]
Hi Jerry,

This change request is for the training calendar page located at https://ibm.github.io/mainframe-downloads/Training/idzrdz-remote-training.html. As you see, the dates are from last year.

From https://community.ibm.com/community/user/ibmz-and-linuxone/groups/community-home/librarydocuments/viewdocument?DocumentKey=b799d462-5fbb-486c-9462-999c8f80292c&Step=1&CommunityKey=336bb81c-ac97-46d5-95bb-319e41258fbe&ReturnUrl=%2fcommunity%2fuser%2fibmz-and-linuxone%2fviewdocument%2fidz-adfz-remote-training-calendar%3fCommunityKey%3db0dae4a8-74eb-44ac-86c7-90f3cd32909a%26tab%3dlibrarydocuments, can you please go to the "IDz/ADFz Entry-Level/Experienced User Training Schedule" section and replace the classes dates with these ones?

We have new class dates from March 1 all the way to May 31.

Let me know if anything is unclear.

Thank you,
Shabbir

**Comment by jerryxz-ibm** [comment]
Training table updated.
