### ISSUE TITLE
web proxy access

### ISSUE THREAD

**Issue by prab99** [IBM/mainframe-downloads#412]
I am targeting a single eclipse distribution for all our Mainframe components viz. IBM explorer for z/OS, IBM MQ explorer, IBM CICS explorer, IBM data studio, IBM debug for z/OS, IBM file Manager for zOS, IBM Fault Analyzer for z/OS, IBM Monitoring and diagnostics tools - Health Center using IBM AQUA 3.3. My installation gets blocked by our corporate proxy + firewalls. Is there a list of all the repository locations that I can plan access so that my installation and packages refresh is not Firewalled. 

<arg>Download http://public.dhe.ibm.com/ibmdl/export/pub/software/htp/zos/tools/aqua3.2/repository.config to C:\Users\test\AppData\Local\Temp\cicdip_test\1658809302217\nf\cicURLLrepository.config5479751411963239915config</arg><arg>java.net.ConnectException: Connection timed out: connect
  at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
  at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:96)
  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:380)
  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:236)

**Comment by jerryxz-ibm** [comment]
Hi @prab99 , we don't really have any exhaustive list for IBM Aqua repositories. However, you could follow these steps to download a single zip package which includes all the latest products of Aqua 3.3, then you can choose and install your target products locally with it:
1. Go to the download wizard in IBM Mainframe Downloads website: [https://ibm.github.io/mainframe-downloads/eclipse-tools.html](https://ibm.github.io/mainframe-downloads/eclipse-tools.html)
2. Select any of the Aqua 3.3 supported product, e.g. "IBM Explorer for z/OS"
3. Select "Aqua 3.3"
4. Select "Eclipse p2"
5. Select "Hosting an internal repository"
6. Then in step 2 of "Download and install", you can download the entire P2 zip. 

BTW, this Github repo is not intended to track issues related to IBM Aqua product downloads, as it serves only as a static website to provide redirections to IBM Public DHE download server where all Aqua products are hosted.
