### ISSUE TITLE
Update release date of a tech doc

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#44]
Hi Jerry,

Here:
https://ibm.github.io/mainframe-downloads/DevOps_Acceleration_Program/resources.html
In the Design category, th first tile is about "Managing the build scope...". We released a new version of it, so can you please update the date on the tile from Dec 2020 to Feb 2021?

Thank you,
Shabbir

**Comment by jerryxz-ibm** [comment]
Updated.
