### ISSUE TITLE
Add new tech doc to DAP resources page

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#46]
Hi Jerry,

On the DAP resources page, https://ibm.github.io/mainframe-downloads/DevOps_Acceleration_Program/resources.html, in the Tutorials section, can you please add a new tile (make it the first tile please) called "Azure DevOps and IBM Dependency Based Build Integration". 
The link to that document is at https://www.ibm.com/support/pages/node/6422813

Thank you,
Shabbir

**Comment by jerryxz-ibm** [comment]
New card added for the link.
