### ISSUE TITLE
Fix a link on the ADFz Resources Page

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#49]
Hi Jerry,

On the following page:
https://ibm.github.io/mainframe-downloads/Training/adfz-learning-resources.html

There is a link under "Information about the IBM (no-charge) public training classes", which goes to the Community page from Jon. I would like it to go to our Github page.

Can you change that link to go to https://ibm.github.io/mainframe-downloads/Training/idzrdz-remote-training.html instead?

Thank you,
Shabbir

**Comment by jerryxz-ibm** [comment]
Fixed.
