### ISSUE TITLE
DAP page - please add new tech doc under Resources

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#5]
DAP page: https://ibm.github.io/mainframe-downloads/DevOps_Acceleration_Program/devops-acceleration-program.html

When you click on Resources (https://ibm.github.io/mainframe-downloads/DevOps_Acceleration_Program/resources.html), you will see two Tech Docs today. I want to have a third one added as a new tile, with the title "Managing git credentials in Jenkins to access the central git provider". The link should go to http://w3-03.ibm.com/support/techdocs/atsmastr.nsf/WebIndex/TD106439

**Comment by jerryxz-ibm** [comment]
Issue resolved.
