### ISSUE TITLE
Add tile for new tech doc to Resources page

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#50]
Hi Jerry,

On the DAP resources page, https://ibm.github.io/mainframe-downloads/DevOps_Acceleration_Program/resources.html, in the **Design** section, can you please add a new tile (make it the first tile please) called "Advanced Build and Migration recipes with DBB and zAppBuild".
The link to that document is at https://www.ibm.com/support/pages/node/6427617

Thank you,
Shabbir

**Comment by shabbirmoledina** [comment]
Actually, please create a new section for this document. Call it "zAppBuild" and put it in between the Tutorials and Design section. 
I will have two more documents that will go in this section later

**Comment by jerryxz-ibm** [comment]
New section and tile added.
