### ISSUE TITLE
Update privacy statements on landing pages

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#52]
Hi Jerry,

On the Training main page https://ibm.github.io/mainframe-downloads/Training/Training.html, there are 4 tiles which lead to courses. Each of those links takes you to a landing page which has information on Badge Overview, Badge Description etc.

In the Badge Description section, there are two sub-areas which require some small changes as show below. Can you please do this for all 4 landing pages? Basically, we are replacing the references of **Acclaim** with **Credly**.

**Badge Queries**
 <leave the first statement alone but change the second and third lines as follows. In the third line, note that "here" is a link, so please maintain that>

Credly Support: For questions related to your Credly badge earner account and profile, as well as issues related to claiming your badge after receiving a notification, go to support.credly.com.

For Frequently Asked Questions about the IBM Digital Badge Program, click here. 

**Badge Privacy Statement**
<change the entire paragraph>

IBM leverages the services of Credly, a 3rd party data processor authorized by IBM and located in the United States, to assist in the administration of the IBM Digital Badge program. In order to issue you an IBM Digital Badge, your personal information (name, email address, and badge earned) will be shared with Credly. You will receive an email notification from Credly with instructions for claiming the badge. Your personal information is used to issue your badge and for program reporting and operational purposes. It will be handled in a manner consistent with IBM privacy practices. The IBM Privacy Statement can be viewed here: https://www.ibm.com/privacy/us/en/.  IBM employees can view the IBM Internal Privacy Statement here: https://w3.ibm.com/w3publisher/w3-privacy-notice. 

If you prefer to get any clarification on this via a quick Webex call, let me know and we can do that.

**Comment by jerryxz-ibm** [comment]
Hi Shabbir, the updates are made to live site. Please take a look. If things work, feel free to close.

**Comment by shabbirmoledina** [comment]
Looks good, thank you!
