### ISSUE TITLE
DAP page - Please add new Tech Doc under Resources

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#6]
DAP page: https://ibm.github.io/mainframe-downloads/DevOps_Acceleration_Program/devops-acceleration-program.html

When you click on Resources (https://ibm.github.io/mainframe-downloads/DevOps_Acceleration_Program/resources.html), you will see some Tech Docs today. I want to have another one added as a new tile, with the title "Integrating IBM z/OS platform in CI pipelines with Gitlab". The link should go to http://www-03.ibm.com/support/techdocs/atsmastr.nsf/WebIndex/WP102827

**Comment by jerryxz-ibm** [comment]
Issue resolved.
