### ISSUE TITLE
Create New Landing Page for APA

### ISSUE THREAD

**Issue by jiachunx** [IBM/mainframe-downloads#60]
Similar to the ADDI landing page which is at https://ibm.github.io/mainframe-downloads/Training/addi-self-paced-learning.html, please create a new one for APA.
Please make the link be https://ibm.github.io/mainframe-downloads/Training/aPA-self-paced-learning.html.

Content to change:

The title should change to **IBM Application Performance Analyzer for z/OS Training Course**
The subtitle should change to **system constraints and assist in improving application performance with IBM APA**
Above the **Badge Overview** section, create a **Launch the course** section, with the description pointing to https://learn.ibm.com/course/view.php?id=8989
**Badge Overview** section - update description to Digital credentials are the future and they are here for Application Performance Analyzer (APA). Digital credentials are transforming how IBM is engaging, recognizing and managing talent. The course is designed to help z/OS systems programmers identify system constraints and assist in improving application performance with IBM APA.
**Badge Description** section - update Description to
The badge holder has successfully completed the self paced online course and zTrial Lab, covering the following modules:
Upon completion of this course, students will have the foundational knowledge on following topics:
•	Module 1 – Introduction to IBM Application Performance Analyzer for z/OS
•	Module 2 – Interacting with APA
•	Module 3 – Getting Started
•	Module 4 – Working with Observations
•	Module 5 – Source-Program Mapping 
•	Module 6 – Generating Variance Reports
•	Module 7 – Best Practices and Performance Analysis Strategies Part 1 of 2
•	Module 8 – Best Practices and Performance Analysis Strategies Part 1 of 2
•	Module 9 – Managing Performance Reports
•	Module 10 – zTrial and Badge Quiz

**What it takes to earn this badge**
What it takes to earn this badge
Successful completion of the Application Performance Analyzer (APA) online self paced course and clearing the badge quiz assessment.
Please access the following URL to launch the course: https://learn.ibm.com/course/view.php?id=8989

You will receive your badge within 10 business days of completing the training curriculum. This badge can be obtained by any IBM employee or non-IBM employee.
**More about the IBM Digital Badge program**
IBM has established a Digital Badge Program to recognise our employees' significant achievements and skills attainment. IBM credentials are recognized, respected and valued globally in the IT industry. This program will enable you to easily and quickly share verified proof of your achievement both within IBM and externally. Where applicable, your IBM credentials will be represented by a digital image that contains verified metadata describing your qualifications and the rigorous process necessary to earn them.
**Badge Queries**
For questions about the DBB Basics badge program, such as a missing or incorrect badge or how to earn the badge, contact shabbirm@ca.ibm.com, chrishoina@ibm.com
or jiachun.xiang@ibm.com
Credly Support: For questions related to your Credly badge earner account and profile, as well as issues related to claiming your badge after receiving a notification, go to support.credly.com.
For Frequently Asked Questions about the IBM Digital Badge Program, click here.
**Badge Privacy Statement**
IBM leverages the services of Credly, a 3rd party data processor authorized by IBM and located in the United States, to assist in the administration of the IBM Digital Badge program. In order to issue you an IBM Digital Badge, your personal information (name, email address, and badge earned) will be shared with Credly. You will receive an email notification from Credly with instructions for claiming the badge. Your personal information is used to issue your badge and for program reporting and operational purposes. It will be handled in a manner consistent with IBM privacy practices. The IBM Privacy Statement can be viewed here: https://www.ibm.com/privacy/us/en/ IBM employees can view the IBM Internal Privacy Statement here: https://w3.ibm.com/w3publisher/w3-privacy-notice .

**Comment by jiachunx** [comment]
@jerryxz-ibm

**Comment by shabbirmoledina** [comment]
Small changes:
The link should be https://ibm.github.io/mainframe-downloads/Training/apa-self-paced-learning.html

Subtitle should be:
Improving application performance with IBM APA

**Comment by jerryxz-ibm** [comment]
New page created at: https://ibm.github.io/mainframe-downloads/Training/apa-self-paced-learning.html
