### ISSUE TITLE
DAP Resources Page - Addition of new assets

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#61]
Hi Jerry,
On the DAP resources website, https://ibm.github.io/mainframe-downloads/DevOps_Acceleration_Program/resources.html, can you please do the following:

The last section is called Webinar Replays. Can you rename that to Webinars/Demos please?
Also, please add two new tiles for Gitlab demos we recently created.
https://mediacenter.ibm.com/media/GitLab+and+IBM+Z+DevOps+SolutionsB+Overview/1_oxj8eseu - GitLab and IBM Z DevOps Solutions; Overview
https://mediacenter.ibm.com/media/GitLab+and+IBM+Z+DevOps+SolutionsB+CI+CD+Pipeline/1_qjtm421u - GitLab and IBM Z DevOps Solutions; CI/CD Pipeline

**Comment by jerryxz-ibm** [comment]
New tiles created.
