### ISSUE TITLE
DAP page - Please add another Tech Doc to the Resources section

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#7]
DAP page: https://ibm.github.io/mainframe-downloads/DevOps_Acceleration_Program/devops-acceleration-program.html

When you click on Resources (https://ibm.github.io/mainframe-downloads/DevOps_Acceleration_Program/resources.html), you will see some Tech Docs today. I want to have another one added as a new tile, with the title "Integrating Unit Tests into an open and modern CI/CD pipeline". The link should go to http://www-03.ibm.com/support/techdocs/atsmastr.nsf/WebIndex/TD106441

**Comment by jerryxz-ibm** [comment]
Issue resolved.
