### ISSUE TITLE
Changes needed on the DBB Training landing page

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#8]
For this page https://ibm.github.io/mainframe-downloads/Training/dbb-self-paced-learning.html, I would like to request some small changes:

1) Above the **Badge Overview** section, create one called **Launch the course** and add https://www.onlinedigitallearning.com/course/view.php?id=5146 in its description section

2) In the **Badge Queries** section, in the first paragraph, replace 
_For questions about the DBB Basics badge program, such as a missing or incorrect badge or how to earn the badge, contact brice@ibm.com, jayakarm@ibm.com, shikunli@cn.ibm.com_
with 
_For questions about the DBB Basics badge program, such as a missing or incorrect badge or how to earn the badge, contact shabbirm@ca.ibm.com, shikunli@cn.ibm.com_

3) In the **Badge Queries** section, remove the third paragraph which is _General Badge Program inquiries: For general inquiries related to the IBM Digital Badge Program, contact badge@us.ibm.com._

**Comment by jerryxz-ibm** [comment]
Issue resolved.
