### ISSUE TITLE
Replace email address on DBB badge course website

### ISSUE THREAD

**Issue by jiachunx** [IBM/mainframe-downloads#86]
Hi,

This change request is for the training calendar page located at [.](https://ibm.github.io/mainframe-downloads/Training/dbb-self-paced-learning.html) As you see, the dates are from last year.

From [,](https://ibm.github.io/mainframe-downloads/Training/dbb-self-paced-learning.html) can you please go to replace Shi Kun's email address with Christine's?

Let me know if anything is unclear.

Thank you,
Jiachun Xiang

**Comment by jerryxz-ibm** [comment]
@jiachunx Can you please check if this task is done? Please close it in case nothing else needed. Thanks.
