### ISSUE TITLE
Changes to IDz badge landing page

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#9]
For this page https://ibm.github.io/mainframe-downloads/DevOps_Acceleration_Program/idz-self-paced-learning.html, I would like to request some small changes:

1) Above the **Badge Overview** section, create one called **Launch the course** and add _https://www.onlinedigitallearning.com/course/view.php?id=5403_ in its description section

2) In the Badge Queries section, in the first paragraph, replace
_For questions about the IDz Basics badge program, such as a missing or incorrect badge or how to earn the badge, contact Christopher.Sayles@ibm.com, jayakarm@ibm.com_
with
_For questions about the IDz Basics badge program, such as a missing or incorrect badge or how to earn the badge, contact Christopher.Sayles@ibm.com, shabbirm@ca.ibm.com_

3) In the Badge Queries section, remove the third paragraph which is _General Badge Program inquiries: For general inquiries related to the IBM Digital Badge Program, contact badge@us.ibm.com_.

**Comment by jerryxz-ibm** [comment]
Issue resolved.
